version: '3'
services:
  proxy:
    image: jwilder/nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "80:80"
  app:
    environment:
      - VIRTUAL_HOST=${APP_URL}
    image: nicolaidavies/douma-app
    expose:
      - "80"
  api:
    environment:
      - VIRTUAL_HOST=${API_URL}
      - MONGODB_URI
      - SHEETS_URL
      - PORT=3000
      - SECRET=very_secret
    image: nicolaidavies/douma-api
    command: npm run start
    expose:
     - "3000"