version: '3'
services:
  proxy:
    image: jwilder/nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - hosts:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
  ssl:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - certs:/etc/nginx/certs:rw
      - hosts:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
  app:
    environment:
      - VIRTUAL_HOST=${APP_URL}
      - LETSENCRYPT_HOST=${APP_URL}
      - LETSENCRYPT_EMAIL=${SSL_EMAIL}
    image: nicolaidavies/douma-app
    expose:
      - "80"
  api:
    environment:
      - LETSENCRYPT_HOST=${API_URL}
      - LETSENCRYPT_EMAIL=${SSL_EMAIL}
      - VIRTUAL_HOST=${API_URL}
      - MONGODB_URI
      - SHEETS_URL
      - PORT=3000
      - SECRET=very_secret
    image: nicolaidavies/douma-api
    command: npm run start
    expose:
      - "3000"
volumes:
  certs:
  hosts:
  html: